# Hello World!


### This is Coursera IBM Applied Data Science Capstone Week 3 Peer-graded Assignment: Segmenting and Clustering Neighborhoods in Toronto

In this assignment we should explore and cluster the neighborhoods in Toronto by scrapping postal code of Toronto using Wikipedia data.



## 01- Preparing the Dataframe:

In [12]:
#Importing dataframe libraries
import numpy as np 
import pandas as pd 
import requests 
from bs4 import BeautifulSoup

Libraries imported.

In [13]:
# Scrapping postal code of Canda
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
dataSource = requests.get(url).text
soup = BeautifulSoup(source, 'xml')
table=soup.find('table')
column_names = ['Postalcode','Borough','Neighborhood']
df = pd.DataFrame(columns = column_names)

In [24]:
for tr_cell in table.find_all('tr'):
    row_data=[]
    for td_cell in tr_cell.find_all('td'):
        row_data.append(td_cell.text.strip())
    if len(row_data)==3:
        df.loc[len(df)] = row_data
        
        
df.head()

  Postalcode           Borough                                 Neighborhood
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [30]:
# Cliening data by removing 'Not assigned' from Borough column
df1 = df.dropna()
empty = 'Not assigned'
df1 = df1[(df.Postalcode != empty ) & (df.Borough != empty) & (df.Neighborhood != empty)]

df1.head()

  Postalcode           Borough                                 Neighborhood
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [33]:
def neighborhood_list(grouped):    
    return ', '.join(sorted(grouped['Neighborhood'].tolist()))
                    
grp = df.groupby(['Postalcode', 'Borough'])
df2 = grp.apply(neighborhood_list).reset_index(name='Neighborhood')

df2.head()

  Postalcode      Borough                            Neighborhood
0        M1B  Scarborough                          Malvern, Rouge
1        M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2        M1E  Scarborough       Guildwood, Morningside, West Hill
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae